language: java

jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

jobs:
  include:
  - script: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify
    name: Unit, Integration Tests & Quality